#!python
import os

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=[os.path.join(os.getcwd(), "src")])

sources = Glob("src/*.cpp")

platform = env["platform"]
target = env["target"]
arch = env["arch"]

if target == "template_debug":
    config = "debug"
elif target == "template_release":
    config = "release"
else:
    config = target

if platform == "windows":
    lib_name = "native_hash.windows.{}.{}".format(config, arch)
elif platform == "android":
    lib_name = "native_hash.android.{}.{}".format(config, arch)
else:
    lib_name = "native_hash.{}.{}.{}".format(platform, config, arch)

library = env.SharedLibrary(target=os.path.join("bin", lib_name), source=sources)
Default(library) 
