#!python
import os

godot_cpp_sconstruct = os.path.join("godot-cpp", "SConstruct")

if not os.path.exists(godot_cpp_sconstruct):
    raise Exception(
        "godot-cpp is missing. "
        "Run 'git submodule update --init --recursive' "
        "or clone godot-cpp into native/extension/godot-cpp."
    )

env = SConscript(godot_cpp_sconstruct)
env.Append(CPPPATH=[os.path.join(os.getcwd(), "src")])

sources = Glob("src/*.cpp")

platform = env["platform"]
target = env["target"]
arch = env["arch"]

if target == "template_debug":
    config = "debug"
elif target == "template_release":
    config = "release"
else:
    config = target

if platform == "windows":
    lib_name = "native_hash.windows.{}.{}".format(config, arch)
elif platform == "android":
    lib_name = "native_hash.android.{}.{}".format(config, arch)
else:
    lib_name = "native_hash.{}.{}.{}".format(platform, config, arch)

library = env.SharedLibrary(target=os.path.join("bin", lib_name), source=sources)
Default(library)
